### ISSUE TITLE
Specs

### ISSUE THREAD

**Issue by dzucconi** [dzucconi/calendrical#3]

**Comment by dzucconi** [comment]
https://github.com/dzucconi/calendrical/pull/8 Gets us started here (thanks! @catull).

I'm going to need to follow up with more coverage and an automated build on Travis soon. (A headless runner like Mocha is probably preferable to Jasmine as well IMO)

**Comment by catull** [comment]
Sure, I looked at both Jasmine and Mocha, thought jasmine was simpler.
But, I can get friendlier towards Mocha if the bribe is attractive :-).
