### ISSUE TITLE
Errors in Week-day and Gregorian month representation

### ISSUE THREAD

**Issue by catull** [dzucconi/calendrical#5]
The code displays the week-days 2 days ahead, so an effective Monday is displayed as Wednesday etc.

The Gregorian date is one month off, e.g. April 5th 2016 is rendered as { month: 3, day: 5, year: 2016 }.
The reason is that JavaScript's Date months start from 0, so Date#getMonth() is one lower than the effective month when displayed as the MM pattern.

**Comment by dzucconi** [comment]
Closed with https://github.com/dzucconi/calendrical/pull/6
